- name: install docker
  apt:
    name: docker
    state: present
  become: true

- name: Enable and start docker service
  systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
  become: true

- name: Reboot if needed for docker group changes
  reboot:
    msg: "Rebooting to apply docker group changes"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: "docker ps"
  when: "'docker' in ansible_facts['groups']['docker'] and ansible_facts['user'] == 'ec2-user'"
